add npk import course
Nuclei-Software/nuclei-tool-guide pull request #10
Opened 2024-10-31 07:15 UTC by laomaolaile

add npk import course

2024-10-31 08:19 UTC, fanghuaqi commented on source/ide/advanceeusage.rst
> +在Nuclei Studio中，通过给工程中的文件或者文件夹添加 ``--coverage`` 编译选项编译，在实际开发板上运行，并配合semihost功能则可以收集需要的coverage文件(gcda/gcno文件)，则可以在gcov工具的配合下，以图形化的方式展示。
在实际开发板上运行时，可以配合semihost功能实现文件读写到主机电脑上，就可以收集到需要的coverage文件(gcda/gcno文件)，或者通过Nuclei SDK提供的profiling库来实现将coverage数据打印到串口上，然后通过IDE来解析并保存到主机上。

https://github.com/Nuclei-Software/nuclei-sdk/tree/master/Components/profiling

2024-10-31 08:20 UTC, fanghuaqi commented on source/ide/advanceeusage.rst
> +在Nuclei Studio中，通过带特定的编译选项 ``-pg`` 编译指定源码文件，在实际开发板上运行，并配合semihost功能则可以收集需要的 ``gmon.out`` 文件，在IDE上以图形化的方式展示。
同上问题

2024-10-31 08:20 UTC, fanghuaqi requested changes
source/ide/advanceeusage.rst 文件名typo，需要改下 source/ide/advanceusage.rst

2024-10-31 08:21 UTC, fanghuaqi commented on source/ide/npk.rst
> +首先，点击Nuclei Studio IDE工具栏上的“Nuclei Package Management”按钮，这将打开npk软件包管理页面。在这个页面上，你可以管理和浏览已安装的软件包，以及导入新的软件包。在这里，我们找到并点击“Import”选项。这个选项用于从本地文件系统选择zip类型的软件包。
不要用  "" 这样的中文引号，需要加粗显示就 正常加粗

2024-11-01 03:09 UTC, laomaolaile commented
The above issue has been fixed, please merge to master.

2024-11-01 04:18 UTC, fanghuaqi commented
还是有冲突， 你需要先解决冲突。

2024-11-01 04:18 UTC, fanghuaqi commented
![image](https://github.com/user-attachments/assets/ea690b70-881a-40ec-8e4c-b7745471bec4)

2024-11-01 08:08 UTC, merged